import java.sql.*;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Laguardia
 */
public class logins extends javax.swing.JFrame {
    Connection con;
    ResultSet rs;
    PreparedStatement pst;
    
    /**
     * Creates new form logins
     */
    public logins() {
        initComponents();
    }
    
    public Connection getConnection(){      
        
        try{                                                                        //username //database         =pass no password
            Connection con = (Connection)DriverManager.getConnection("jdbc:mysql://localhost/voting_system","root","");
            return con; 
        }      
        catch(Exception e){          
        }
       
        return null;
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        usertext = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        passtext = new javax.swing.JPasswordField();
        jPanel1 = new javax.swing.JPanel();
        kGradientPanel1 = new keeptoo.KGradientPanel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        usertext.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        usertext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usertextActionPerformed(evt);
            }
        });
        usertext.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                usertextKeyPressed(evt);
            }
        });
        getContentPane().add(usertext, new org.netbeans.lib.awtextra.AbsoluteConstraints(256, 111, 187, -1));

        jLabel1.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ID Number");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(139, 117, -1, -1));

        jLabel2.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Password");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(149, 153, 89, -1));

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        jButton2.setText("LOGIN");
        jButton2.setToolTipText("");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton2MouseEntered(evt);
            }
        });
        jButton2.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                jButton2InputMethodTextChanged(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(254, 201, 190, -1));

        passtext.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        passtext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passtextActionPerformed(evt);
            }
        });
        passtext.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                passtextKeyPressed(evt);
            }
        });
        getContentPane().add(passtext, new org.netbeans.lib.awtextra.AbsoluteConstraints(256, 147, 187, -1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kGradientPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jButton1.setText("Main Menu");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        kGradientPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 320, -1, -1));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Courier New", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText(" Classroom Election");
        kGradientPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 480, 50));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Please Enter Id number and Password");
        kGradientPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, 200, -1));

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton3.setText("Forgot Password");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        kGradientPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 250, 200, -1));

        jPanel1.add(kGradientPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 360));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 360));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void usertextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usertextActionPerformed
        
        String yes="yes";
        String no="no";
        String passid=usertext.getText();
        String login = "SELECT * FROM account WHERE id_number ='"+usertext.getText()+"' AND password = '"+passtext.getText() + " ' AND status = '"+no +"'";
        String already = "SELECT * FROM account WHERE id_number ='"+usertext.getText()+"' AND password = '"+passtext.getText() + " ' AND status = '"+yes +"'";
        String incorrect = "SELECT * FROM account WHERE id_number !='"+usertext.getText()+"' AND password != '"+passtext.getText() + " ' ";        
                   
        try{               
            Connection con = getConnection();                           
            pst = con.prepareStatement(login); 
            
            PreparedStatement pst1= con.prepareStatement(incorrect);                 
            ResultSet rs1;       
            rs1 = pst1.executeQuery();
    
            PreparedStatement pst2= con.prepareStatement(already);    
            ResultSet rs2;                   
            rs2 = pst2.executeQuery();                
            rs = pst.executeQuery();                
                
            if(rs.next()){                 
                rs.close();                
                pst.close();                
                JOptionPane.showMessageDialog(null,"Sucess!");             
                setVisible(false);
              
                new voting(passid).setVisible(true);          
            }                                
            else if (rs2.next()){             
                JOptionPane.showMessageDialog(null, "You already vote!");            
                usertext.setText(null);            
                passtext.setText(null);         
            }                            
            else if (rs1.next()){           
                JOptionPane.showMessageDialog(null, "Incorrect ID number AND Passowrd!");           
                usertext.setText(null);                        
                passtext.setText(null);           
            }       
        }                       
        catch(Exception e){                 
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_usertextActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
                     
        String yes="yes"; 
        String no="no";
        String passid=usertext.getText();              
        String login = "SELECT * FROM account WHERE id_number ='"+usertext.getText()+"' AND password = '"+passtext.getText() + " ' AND status = '"+no +"'";
        String already = "SELECT * FROM account WHERE id_number ='"+usertext.getText()+"' AND password = '"+passtext.getText() + " ' AND status = '"+yes +"'";
        String incorrect = "SELECT * FROM account WHERE id_number !='"+usertext.getText()+"' AND password != '"+passtext.getText() + " ' ";
        
        try{                     
            Connection con = getConnection();           
            pst = con.prepareStatement(login);            
            rs = pst.executeQuery();
            
            PreparedStatement pst1= con.prepareStatement(incorrect);
            ResultSet rs1;        
            rs1 = pst1.executeQuery();
            
            PreparedStatement pst2= con.prepareStatement(already);
            ResultSet rs2;        
            rs2 = pst2.executeQuery();
                   
            if(rs.next()){           
                rs.close();
                pst.close();                
                JOptionPane.showMessageDialog(null,"Sucess!");                
                setVisible(false);              
                new voting(passid).setVisible(true);                        
            }                                    
            else if (rs2.next()){
                JOptionPane.showMessageDialog(null, "You already vote!");
                usertext.setText(null);
                passtext.setText(null);
            }            
            else if (rs1.next()){
                JOptionPane.showMessageDialog(null, "Incorrect ID number AND Passowrd!");                
                usertext.setText(null);
                passtext.setText(null);
            }                  
        }        
        catch(Exception e){                   
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        setVisible(false);
        mainmenu main = new mainmenu();
        main.setVisible(true);       
        main.setLocationRelativeTo(null);

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2MouseEntered

    private void jButton2InputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_jButton2InputMethodTextChanged

        String yes="yes";  
        String no="no";
        String passid=usertext.getText();              
        String login = "SELECT * FROM account WHERE id_number ='"+usertext.getText()+"' AND password = '"+passtext.getText() + " ' AND status = '"+no +"'";
        String already = "SELECT * FROM account WHERE id_number ='"+usertext.getText()+"' AND password = '"+passtext.getText() + " ' AND status = '"+yes +"'";
        String incorrect = "SELECT * FROM account WHERE id_number !='"+usertext.getText()+"' AND password != '"+passtext.getText() + " ' ";
        
        try{                       
            Connection con = getConnection();          
            pst = con.prepareStatement(login);                       
                       
            PreparedStatement pst1= con.prepareStatement(incorrect);
            ResultSet rs1;        
            rs1 = pst1.executeQuery();                                           
               
            PreparedStatement pst2= con.prepareStatement(already);
            ResultSet rs2;         
            rs2 = pst2.executeQuery();                    
            rs = pst.executeQuery();
           
            if(rs.next()){                             
                rs.close();
                pst.close();               
                JOptionPane.showMessageDialog(null,"Sucess!");                              
                setVisible(false);                
                new voting(passid).setVisible(true);            
            }                                  
            else if (rs2.next()){
                JOptionPane.showMessageDialog(null, "You already vote!");
                usertext.setText(null);
                passtext.setText(null);
            }
            else if (rs1.next()){
                JOptionPane.showMessageDialog(null, "Incorrect ID number AND Passowrd!");
                 usertext.setText(null);
                passtext.setText(null);
            }                                                     
        }              
        catch(Exception e){                 
        }     

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2InputMethodTextChanged

    private void passtextKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passtextKeyPressed
       // TODO add your handling code here:
    }//GEN-LAST:event_passtextKeyPressed

    private void usertextKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_usertextKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_usertextKeyPressed

    private void passtextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passtextActionPerformed
         
        String yes="yes";  
        String no="no";
        String passid=usertext.getText();               
        String login = "SELECT * FROM account WHERE id_number ='"+usertext.getText()+"' AND password = '"+passtext.getText() + " ' AND status = '"+no +"'";
        String already = "SELECT * FROM account WHERE id_number ='"+usertext.getText()+"' AND password = '"+passtext.getText() + " ' AND status = '"+yes +"'";
        String incorrect = "SELECT * FROM account WHERE id_number !='"+usertext.getText()+"' AND password != '"+passtext.getText() + " ' ";
        
        try{                      
            Connection con = getConnection();           
            pst = con.prepareStatement(login);
                                              
            PreparedStatement pst1= con.prepareStatement(incorrect);
            ResultSet rs1;         
            rs1 = pst1.executeQuery();
                                   
            PreparedStatement pst2= con.prepareStatement(already);
            ResultSet rs2;         
            rs2 = pst2.executeQuery();                     
            rs = pst.executeQuery();
        
            if(rs.next()){              
                rs.close();
                pst.close();               
                JOptionPane.showMessageDialog(null,"Sucess!");                       
                setVisible(false);                
                new voting(passid).setVisible(true);              
            }           
            else if (rs2.next()){
                JOptionPane.showMessageDialog(null, "You already vote!");
                usertext.setText(null);
                passtext.setText(null);
            }                  
            else if (rs1.next()){
                JOptionPane.showMessageDialog(null, "Incorrect ID number AND Passowrd!");     
                usertext.setText(null);
                passtext.setText(null);
            }                                                   
        }          
        catch(Exception e){                
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_passtextActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        forgot main = new forgot();
        main.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(logins.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(logins.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(logins.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(logins.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new logins().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private keeptoo.KGradientPanel kGradientPanel1;
    private javax.swing.JPasswordField passtext;
    private javax.swing.JTextField usertext;
    // End of variables declaration//GEN-END:variables
}
